
# Fichero de secretos para Streamlit (NO subir a repos p√∫blicos con claves reales)
# En Streamlit Cloud puedes configurar estos valores desde la UI de 'Secrets'.
#
# Ejemplo:
# AEMET_KEY = "tu_api_key_de_aemet"

AEMET_KEY = "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJnYXJyaXdlYkBnbWFpbC5jb20iLCJqdGkiOiI2OTYyNjBhYS1mMDc2LTRhZDQtYmFhZC1kYzRhNTI4NzI0NTIiLCJpc3MiOiJBRU1FVCIsImlhdCI6MTc2MzQxODcwNywidXNlcklkIjoiNjk2MjYwYWEtZjA3Ni00YWQ0LWJhYWQtZGM0YTUyODcyNDUyIiwicm9sZSI6IiJ9.VnqFHQ8BWBZ74xi5RlFWPQCchlRYyctmO2atJrYktHQ"
